parser: babel-eslint
plugins:
  - node
  - import
  - promise
  - flow
extends:
  - '@enkidevs/eslint-config-backend'
rules:
  node/no-unsupported-features/es-syntax: off
  promise/always-return: off
  func-names: off
